"""
Export the trained scikit-learn MLP so the browser simulation can use it.

WHY THIS EXISTS
---------------
The warehouse simulation runs as a single dependency-free HTML file, so it
cannot import scikit-learn. Rather than hand-writing a second, different
network in JavaScript and hoping it behaves like the Python one, this script
dumps the ACTUAL trained weights to JSON. The browser then runs the exact
same arithmetic on the exact same numbers.

That keeps one honest claim: the demand predictor in the demo IS the
scikit-learn MLPClassifier we trained and validated in train_mlp.py.

The network is small enough to make this trivial:

    24 one-hot hour inputs  ->  6 ReLU hidden units  ->  4 softmax outputs

Forward pass, in full:

    h = relu(x @ W0 + b0)
    o = softmax(h @ W1 + b1)

USAGE
-----
    python ml_model/train_mlp.py        # produces artifacts/mlp_zone.joblib
    python ml_model/export_weights.py   # produces artifacts/mlp_weights.json
"""

import json
import os

import joblib
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ARTIFACT_DIR = os.path.join(HERE, "artifacts")
MODEL_PATH = os.path.join(ARTIFACT_DIR, "mlp_zone.joblib")
JSON_PATH = os.path.join(ARTIFACT_DIR, "mlp_weights.json")
JS_PATH = os.path.join(ARTIFACT_DIR, "predict_zone.js")

JS_TEMPLATE = """// Auto-generated by ml_model/export_weights.py - do not edit by hand.
//
// Runs the SAME scikit-learn MLPClassifier we trained in train_mlp.py:
//   24 one-hot hour inputs -> %(hidden)d ReLU hidden units -> %(nout)d softmax outputs
//
// predictZone(14)  ->  { section: "B", scores: { A: .., B: .., C: .., D: .. } }

const MLP_WEIGHTS = %(weights)s;

function predictZone(hour) {
  const W = MLP_WEIGHTS;
  // one-hot the hour exactly the way build_features() does in Python
  const x = new Array(24).fill(0);
  x[((hour %% 24) + 24) %% 24] = 1;

  // hidden layer: h = relu(x . W0 + b0)
  const h = W.b0.map((b, j) => {
    let s = b;
    for (let i = 0; i < 24; i++) s += x[i] * W.W0[i][j];
    return s > 0 ? s : 0;              // ReLU
  });

  // output layer: o = softmax(h . W1 + b1)
  const raw = W.b1.map((b, k) => {
    let s = b;
    for (let j = 0; j < h.length; j++) s += h[j] * W.W1[j][k];
    return s;
  });
  const max = Math.max(...raw);
  const exp = raw.map(v => Math.exp(v - max));
  const sum = exp.reduce((a, b) => a + b, 0);
  const probs = exp.map(v => v / sum);

  const scores = {};
  W.classes.forEach((c, i) => { scores[c] = probs[i]; });
  const best = W.classes[probs.indexOf(Math.max(...probs))];
  return { section: best, scores: scores };
}
"""


def main():
    if not os.path.exists(MODEL_PATH):
        raise SystemExit("No trained model found. Run: python ml_model/train_mlp.py")

    bundle = joblib.load(MODEL_PATH)
    clf = bundle["model"]

    if len(clf.coefs_) != 2:
        raise SystemExit(
            "This exporter assumes exactly one hidden layer; the model has %d weight "
            "matrices. Update JS_TEMPLATE if the architecture changed." % len(clf.coefs_))

    W0, W1 = clf.coefs_
    b0, b1 = clf.intercepts_
    classes = [str(c) for c in clf.classes_]

    weights = {
        "classes": classes,
        "W0": np.asarray(W0).round(6).tolist(),
        "b0": np.asarray(b0).round(6).tolist(),
        "W1": np.asarray(W1).round(6).tolist(),
        "b1": np.asarray(b1).round(6).tolist(),
        "architecture": "24 -> %d (relu) -> %d (softmax)" % (W0.shape[1], W1.shape[1]),
        "source": "sklearn.neural_network.MLPClassifier, see ml_model/train_mlp.py",
    }

    os.makedirs(ARTIFACT_DIR, exist_ok=True)
    with open(JSON_PATH, "w", encoding="utf8") as f:
        json.dump(weights, f, indent=1)

    with open(JS_PATH, "w", encoding="utf8") as f:
        f.write(JS_TEMPLATE % {
            "hidden": W0.shape[1],
            "nout": W1.shape[1],
            "weights": json.dumps(weights, indent=1),
        })

    print("architecture : %s" % weights["architecture"])
    print("classes      : %s" % ", ".join(classes))
    print("wrote        : %s" % os.path.relpath(JSON_PATH, os.path.dirname(HERE)))
    print("wrote        : %s" % os.path.relpath(JS_PATH, os.path.dirname(HERE)))

    # ---- verify the JS maths matches sklearn, hour by hour -----------------
    def js_equivalent(hour):
        x = np.zeros(24, dtype=float)
        x[hour % 24] = 1.0
        h = np.maximum(x @ np.asarray(weights["W0"]) + np.asarray(weights["b0"]), 0)
        raw = h @ np.asarray(weights["W1"]) + np.asarray(weights["b1"])
        e = np.exp(raw - raw.max())
        return classes[int(np.argmax(e / e.sum()))]

    from train_mlp import build_features
    import pandas as pd
    sk = clf.predict(build_features(pd.DataFrame({"hour": list(range(24))})))
    mismatches = [h for h in range(24) if js_equivalent(h) != sk[h]]
    if mismatches:
        raise SystemExit("Exported weights disagree with sklearn at hours: %s" % mismatches)
    print("verified     : exported weights reproduce sklearn's prediction for all 24 hours")


if __name__ == "__main__":
    main()
